import { maskWhere } from '../highlights.js';
import type { BadgeDef } from '../types.js';
import { atomicNumberFromRoll } from './matchers.js';

type AtomicMeta = {
  z: number;
  symbol: string;
  name: string;
  ep: number;
  description: string;
};

/** Approved Z→EP map for Atomic Registry (thematic rarity, uniform 1/1000 odds). */
export const ATOMIC_REGISTRY_META: readonly AtomicMeta[] = [
  {
    z: 1,
    symbol: 'H',
    name: 'Hydrogen',
    ep: 80,
    description: 'Lightest element; fuels stars via fusion.',
  },
  {
    z: 2,
    symbol: 'He',
    name: 'Helium',
    ep: 280,
    description: 'Named for the Sun; second-lightest noble gas.',
  },
  {
    z: 3,
    symbol: 'Li',
    name: 'Lithium',
    ep: 280,
    description: 'Soft alkali metal used in rechargeable batteries.',
  },
  {
    z: 4,
    symbol: 'Be',
    name: 'Beryllium',
    ep: 280,
    description:
      'Named from beryl; toxic and unusually stiff for a light metal.',
  },
  {
    z: 5,
    symbol: 'B',
    name: 'Boron',
    ep: 280,
    description: 'Forms ultra-hard ceramics and the green of emerald.',
  },
  {
    z: 6,
    symbol: 'C',
    name: 'Carbon',
    ep: 80,
    description: 'Basis of organic chemistry and diamond / graphite.',
  },
  {
    z: 7,
    symbol: 'N',
    name: 'Nitrogen',
    ep: 80,
    description: "Makes up most of Earth's atmosphere by volume.",
  },
  {
    z: 8,
    symbol: 'O',
    name: 'Oxygen',
    ep: 80,
    description:
      'Essential for respiration; most abundant element in the crust by mass.',
  },
  {
    z: 9,
    symbol: 'F',
    name: 'Fluorine',
    ep: 280,
    description:
      'Most electronegative element; strengthens tooth enamel as fluoride.',
  },
  {
    z: 10,
    symbol: 'Ne',
    name: 'Neon',
    ep: 280,
    description: 'Gives neon signs their orange-red glow.',
  },
  {
    z: 11,
    symbol: 'Na',
    name: 'Sodium',
    ep: 80,
    description: 'Soft alkali metal of table salt (NaCl).',
  },
  {
    z: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    ep: 80,
    description: 'Central atom in chlorophyll; common light structural metal.',
  },
  {
    z: 13,
    symbol: 'Al',
    name: 'Aluminium',
    ep: 80,
    description:
      "Most abundant metal in Earth's crust; lightweight and corrosion-resistant.",
  },
  {
    z: 14,
    symbol: 'Si',
    name: 'Silicon',
    ep: 80,
    description:
      'Second-most abundant element in the crust; backbone of sand and chips.',
  },
  {
    z: 15,
    symbol: 'P',
    name: 'Phosphorus',
    ep: 80,
    description: 'Key nutrient in DNA and fertilizers.',
  },
  {
    z: 16,
    symbol: 'S',
    name: 'Sulfur',
    ep: 80,
    description: 'Ancient yellow mineral; smells of rotten eggs as H2S.',
  },
  {
    z: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    ep: 80,
    description: 'Green-yellow halogen that disinfects water.',
  },
  {
    z: 18,
    symbol: 'Ar',
    name: 'Argon',
    ep: 280,
    description: 'Third-most abundant gas in dry air; used in welding arcs.',
  },
  {
    z: 19,
    symbol: 'K',
    name: 'Potassium',
    ep: 80,
    description:
      'Alkali metal vital for nerve signals; bananas are famous for it.',
  },
  {
    z: 20,
    symbol: 'Ca',
    name: 'Calcium',
    ep: 80,
    description: 'Builds bones and teeth; soft alkaline-earth metal.',
  },
  {
    z: 21,
    symbol: 'Sc',
    name: 'Scandium',
    ep: 900,
    description: 'First transition metal; named from Scandinavia.',
  },
  {
    z: 22,
    symbol: 'Ti',
    name: 'Titanium',
    ep: 280,
    description:
      'Strong, light metal of aircraft and white paint (as dioxide).',
  },
  {
    z: 23,
    symbol: 'V',
    name: 'Vanadium',
    ep: 280,
    description: 'Named for Vanadis (Freyja); toughens steel alloys.',
  },
  {
    z: 24,
    symbol: 'Cr',
    name: 'Chromium',
    ep: 280,
    description:
      'Gives stainless steel its shine and chrome plating its mirror.',
  },
  {
    z: 25,
    symbol: 'Mn',
    name: 'Manganese',
    ep: 280,
    description: 'From Latin magnes; central to steelmaking and batteries.',
  },
  {
    z: 26,
    symbol: 'Fe',
    name: 'Iron',
    ep: 80,
    description: "Core of Earth and blood's hemoglobin.",
  },
  {
    z: 27,
    symbol: 'Co',
    name: 'Cobalt',
    ep: 280,
    description: 'From kobold folklore; blue pigment and hard magnets.',
  },
  {
    z: 28,
    symbol: 'Ni',
    name: 'Nickel',
    ep: 280,
    description:
      'Coinage and stainless alloys; ferromagnetic like iron and cobalt.',
  },
  {
    z: 29,
    symbol: 'Cu',
    name: 'Copper',
    ep: 80,
    description: 'Reddish coinage metal; superb electrical conductor.',
  },
  {
    z: 30,
    symbol: 'Zn',
    name: 'Zinc',
    ep: 80,
    description: 'Galvanizes steel; essential trace nutrient.',
  },
  {
    z: 31,
    symbol: 'Ga',
    name: 'Gallium',
    ep: 900,
    description: 'Melts in your hand (~30 °C); used in semiconductors.',
  },
  {
    z: 32,
    symbol: 'Ge',
    name: 'Germanium',
    ep: 900,
    description: 'Semiconductor pioneer named after Germany.',
  },
  {
    z: 33,
    symbol: 'As',
    name: 'Arsenic',
    ep: 900,
    description: 'Metalloid poison and medicine; old name arsenicum.',
  },
  {
    z: 34,
    symbol: 'Se',
    name: 'Selenium',
    ep: 900,
    description: 'Named for the Moon (selene); antioxidant nutrient.',
  },
  {
    z: 35,
    symbol: 'Br',
    name: 'Bromine',
    ep: 900,
    description: 'Red-brown liquid halogen at room temperature.',
  },
  {
    z: 36,
    symbol: 'Kr',
    name: 'Krypton',
    ep: 900,
    description: 'Noble gas named for its hidden nature (kryptos).',
  },
  {
    z: 37,
    symbol: 'Rb',
    name: 'Rubidium',
    ep: 900,
    description: 'Soft alkali that ignites in air; used in atomic clocks.',
  },
  {
    z: 38,
    symbol: 'Sr',
    name: 'Strontium',
    ep: 900,
    description: "Alkaline earth of red fireworks and bones' cousin chemistry.",
  },
  {
    z: 39,
    symbol: 'Y',
    name: 'Yttrium',
    ep: 900,
    description:
      'Named for Ytterby, Sweden — a village that named four elements.',
  },
  {
    z: 40,
    symbol: 'Zr',
    name: 'Zirconium',
    ep: 900,
    description:
      'Corrosion-resistant twin of titanium; nuclear cladding metal.',
  },
  {
    z: 41,
    symbol: 'Nb',
    name: 'Niobium',
    ep: 900,
    description: 'Named for Niobe; superconducting when pure.',
  },
  {
    z: 42,
    symbol: 'Mo',
    name: 'Molybdenum',
    ep: 900,
    description: 'Essential for enzymes; strengthens steel.',
  },
  {
    z: 43,
    symbol: 'Tc',
    name: 'Technetium',
    ep: 8000,
    description: 'First artificial element; name means artificial.',
  },
  {
    z: 44,
    symbol: 'Ru',
    name: 'Ruthenium',
    ep: 900,
    description: 'Platinum-group metal from ruthenia (Russia).',
  },
  {
    z: 45,
    symbol: 'Rh',
    name: 'Rhodium',
    ep: 900,
    description: 'Rare platinum-group metal; catalytic converters love it.',
  },
  {
    z: 46,
    symbol: 'Pd',
    name: 'Palladium',
    ep: 900,
    description: 'White noble metal for catalysts and fine jewelry.',
  },
  {
    z: 47,
    symbol: 'Ag',
    name: 'Silver',
    ep: 280,
    description: 'Classic coinage metal; best electrical conductor.',
  },
  {
    z: 48,
    symbol: 'Cd',
    name: 'Cadmium',
    ep: 900,
    description: 'Toxic soft metal once used in pigments and batteries.',
  },
  {
    z: 49,
    symbol: 'In',
    name: 'Indium',
    ep: 900,
    description:
      'Soft metal that screams when bent; LCD transparent electrodes (ITO).',
  },
  {
    z: 50,
    symbol: 'Sn',
    name: 'Tin',
    ep: 280,
    description: 'Ancient metal of bronze; resists corrosion.',
  },
  {
    z: 51,
    symbol: 'Sb',
    name: 'Antimony',
    ep: 900,
    description: 'Metalloid of type metal and flame-retardant compounds.',
  },
  {
    z: 52,
    symbol: 'Te',
    name: 'Tellurium',
    ep: 900,
    description: 'Named for Earth (tellus); semiconductor cousin of selenium.',
  },
  {
    z: 53,
    symbol: 'I',
    name: 'Iodine',
    ep: 280,
    description: 'Halogen essential for thyroid hormones.',
  },
  {
    z: 54,
    symbol: 'Xe',
    name: 'Xenon',
    ep: 900,
    description: 'Noble gas used in bright lamps and ion thrusters.',
  },
  {
    z: 55,
    symbol: 'Cs',
    name: 'Caesium',
    ep: 900,
    description: 'Softest alkali; first element discovered by spectroscopy.',
  },
  {
    z: 56,
    symbol: 'Ba',
    name: 'Barium',
    ep: 280,
    description: 'Heavy alkaline earth of green fireworks and X-ray contrast.',
  },
  {
    z: 57,
    symbol: 'La',
    name: 'Lanthanum',
    ep: 4000,
    description: 'Namesake of the lanthanide series.',
  },
  {
    z: 58,
    symbol: 'Ce',
    name: 'Cerium',
    ep: 4000,
    description:
      'Most abundant rare earth; catalytic converters and glass polish.',
  },
  {
    z: 59,
    symbol: 'Pr',
    name: 'Praseodymium',
    ep: 4000,
    description: 'Green salts; name from Greek prasinos (leek-green).',
  },
  {
    z: 60,
    symbol: 'Nd',
    name: 'Neodymium',
    ep: 4000,
    description: 'Strong permanent magnets with iron and boron.',
  },
  {
    z: 61,
    symbol: 'Pm',
    name: 'Promethium',
    ep: 4000,
    description: 'Radioactive lanthanide with no stable isotopes.',
  },
  {
    z: 62,
    symbol: 'Sm',
    name: 'Samarium',
    ep: 4000,
    description:
      'Named for Samarski; used in magnets and nuclear control rods.',
  },
  {
    z: 63,
    symbol: 'Eu',
    name: 'Europium',
    ep: 4000,
    description: 'Named for Europe; red phosphors in old TV tubes.',
  },
  {
    z: 64,
    symbol: 'Gd',
    name: 'Gadolinium',
    ep: 4000,
    description: 'Named for Gadolin; MRI contrast agents use its compounds.',
  },
  {
    z: 65,
    symbol: 'Tb',
    name: 'Terbium',
    ep: 4000,
    description: 'Named for Ytterby; green phosphors.',
  },
  {
    z: 66,
    symbol: 'Dy',
    name: 'Dysprosium',
    ep: 4000,
    description: 'Hard magnetic rare earth; lasers and nuclear control.',
  },
  {
    z: 67,
    symbol: 'Ho',
    name: 'Holmium',
    ep: 4000,
    description: 'Named for Stockholm (Holmia).',
  },
  {
    z: 68,
    symbol: 'Er',
    name: 'Erbium',
    ep: 4000,
    description: 'Named for Ytterby; fiber-optic amplifiers.',
  },
  {
    z: 69,
    symbol: 'Tm',
    name: 'Thulium',
    ep: 4000,
    description:
      'Named for Thule, the mythic north; scarcest stable lanthanide.',
  },
  {
    z: 70,
    symbol: 'Yb',
    name: 'Ytterbium',
    ep: 4000,
    description: 'Named for Ytterby; atomic clocks and lasers.',
  },
  {
    z: 71,
    symbol: 'Lu',
    name: 'Lutetium',
    ep: 4000,
    description: 'Last lanthanide; densest stable rare earth.',
  },
  {
    z: 72,
    symbol: 'Hf',
    name: 'Hafnium',
    ep: 2500,
    description: 'Chemical twin of zirconium; found with zircon.',
  },
  {
    z: 73,
    symbol: 'Ta',
    name: 'Tantalum',
    ep: 2500,
    description:
      'Extremely corrosion-resistant; capacitors and surgical tools.',
  },
  {
    z: 74,
    symbol: 'W',
    name: 'Tungsten',
    ep: 2500,
    description: 'Highest melting point of all metals; light-bulb filaments.',
  },
  {
    z: 75,
    symbol: 'Re',
    name: 'Rhenium',
    ep: 2500,
    description:
      'Last stable element discovered (1925); dense refractory metal.',
  },
  {
    z: 76,
    symbol: 'Os',
    name: 'Osmium',
    ep: 2500,
    description: 'Densest naturally occurring element.',
  },
  {
    z: 77,
    symbol: 'Ir',
    name: 'Iridium',
    ep: 2500,
    description: 'Corrosion-proof platinum-group metal; spark plugs.',
  },
  {
    z: 78,
    symbol: 'Pt',
    name: 'Platinum',
    ep: 2500,
    description: 'Noble catalyst metal; denser than gold.',
  },
  {
    z: 79,
    symbol: 'Au',
    name: 'Gold',
    ep: 280,
    description: 'Classic precious metal; chemical symbol from Latin aurum.',
  },
  {
    z: 80,
    symbol: 'Hg',
    name: 'Mercury',
    ep: 280,
    description: 'Only metal liquid near room temperature.',
  },
  {
    z: 81,
    symbol: 'Tl',
    name: 'Thallium',
    ep: 2500,
    description: 'Toxic soft metal; once in rat poison and semiconductors.',
  },
  {
    z: 82,
    symbol: 'Pb',
    name: 'Lead',
    ep: 280,
    description: 'Ancient dense metal; Latin plumbum gives the symbol Pb.',
  },
  {
    z: 83,
    symbol: 'Bi',
    name: 'Bismuth',
    ep: 2500,
    description: 'Heaviest stable element; oddly not very toxic.',
  },
  {
    z: 84,
    symbol: 'Po',
    name: 'Polonium',
    ep: 2500,
    description: 'Named for Poland; intensely radioactive.',
  },
  {
    z: 85,
    symbol: 'At',
    name: 'Astatine',
    ep: 2500,
    description: 'Rarest natural halogen; name from Greek for unstable.',
  },
  {
    z: 86,
    symbol: 'Rn',
    name: 'Radon',
    ep: 2500,
    description: 'Dense radioactive noble gas from decaying radium.',
  },
  {
    z: 87,
    symbol: 'Fr',
    name: 'Francium',
    ep: 2500,
    description: 'Most unstable natural alkali; named for France.',
  },
  {
    z: 88,
    symbol: 'Ra',
    name: 'Radium',
    ep: 2500,
    description: 'Discovered by the Curies; glows from its own radioactivity.',
  },
  {
    z: 89,
    symbol: 'Ac',
    name: 'Actinium',
    ep: 4000,
    description: 'Namesake of the actinide series.',
  },
  {
    z: 90,
    symbol: 'Th',
    name: 'Thorium',
    ep: 4000,
    description:
      'Common radioactive fuel and lantern-mantle metal historically.',
  },
  {
    z: 91,
    symbol: 'Pa',
    name: 'Protactinium',
    ep: 4000,
    description: 'Between thorium and uranium; name means first actinide.',
  },
  {
    z: 92,
    symbol: 'U',
    name: 'Uranium',
    ep: 4000,
    description: 'Named for Uranus; primary nuclear fuel.',
  },
  {
    z: 93,
    symbol: 'Np',
    name: 'Neptunium',
    ep: 8000,
    description: 'Named for Neptune; first transuranic element synthesized.',
  },
  {
    z: 94,
    symbol: 'Pu',
    name: 'Plutonium',
    ep: 8000,
    description: 'Named for Pluto; fissile fuel of bombs and reactors.',
  },
  {
    z: 95,
    symbol: 'Am',
    name: 'Americium',
    ep: 8000,
    description: 'Named for the Americas; smoke-detector isotope Am-241.',
  },
  {
    z: 96,
    symbol: 'Cm',
    name: 'Curium',
    ep: 8000,
    description: 'Named for the Curies; intense alpha emitter.',
  },
  {
    z: 97,
    symbol: 'Bk',
    name: 'Berkelium',
    ep: 8000,
    description: 'Named for Berkeley, California.',
  },
  {
    z: 98,
    symbol: 'Cf',
    name: 'Californium',
    ep: 8000,
    description: 'Named for California; neutron source for startups.',
  },
  {
    z: 99,
    symbol: 'Es',
    name: 'Einsteinium',
    ep: 8000,
    description: 'Named for Einstein; fallout from the first H-bomb test.',
  },
  {
    z: 100,
    symbol: 'Fm',
    name: 'Fermium',
    ep: 8000,
    description:
      'Named for Fermi; first element found only in lab debris of that test.',
  },
  {
    z: 101,
    symbol: 'Md',
    name: 'Mendelevium',
    ep: 8000,
    description: 'Named for Mendeleev, father of the periodic table.',
  },
  {
    z: 102,
    symbol: 'No',
    name: 'Nobelium',
    ep: 8000,
    description: 'Named for Alfred Nobel.',
  },
  {
    z: 103,
    symbol: 'Lr',
    name: 'Lawrencium',
    ep: 8000,
    description: 'Named for Ernest Lawrence; last actinide.',
  },
  {
    z: 104,
    symbol: 'Rf',
    name: 'Rutherfordium',
    ep: 8000,
    description: 'Named for Rutherford; first transactinide.',
  },
  {
    z: 105,
    symbol: 'Db',
    name: 'Dubnium',
    ep: 8000,
    description: 'Named for Dubna, Russia.',
  },
  {
    z: 106,
    symbol: 'Sg',
    name: 'Seaborgium',
    ep: 8000,
    description: 'Named for Glenn Seaborg — while he was still alive.',
  },
  {
    z: 107,
    symbol: 'Bh',
    name: 'Bohrium',
    ep: 8000,
    description: 'Named for Bohr; superheavy transition metal.',
  },
  {
    z: 108,
    symbol: 'Hs',
    name: 'Hassium',
    ep: 8000,
    description: 'Named from Latin hassia (Hesse, Germany).',
  },
  {
    z: 109,
    symbol: 'Mt',
    name: 'Meitnerium',
    ep: 8000,
    description: 'Named for Lise Meitner.',
  },
  {
    z: 110,
    symbol: 'Ds',
    name: 'Darmstadtium',
    ep: 8000,
    description: 'Named for Darmstadt, Germany.',
  },
  {
    z: 111,
    symbol: 'Rg',
    name: 'Roentgenium',
    ep: 8000,
    description: 'Named for Röntgen, discoverer of X-rays.',
  },
  {
    z: 112,
    symbol: 'Cn',
    name: 'Copernicium',
    ep: 8000,
    description: 'Named for Copernicus.',
  },
  {
    z: 113,
    symbol: 'Nh',
    name: 'Nihonium',
    ep: 8000,
    description: 'Named for Japan (Nihon); first element named in East Asia.',
  },
  {
    z: 114,
    symbol: 'Fl',
    name: 'Flerovium',
    ep: 8000,
    description: 'Named for Flerov Laboratory of Nuclear Reactions.',
  },
  {
    z: 115,
    symbol: 'Mc',
    name: 'Moscovium',
    ep: 8000,
    description: 'Named for Moscow oblast (Moscovia).',
  },
  {
    z: 116,
    symbol: 'Lv',
    name: 'Livermorium',
    ep: 8000,
    description: 'Named for Lawrence Livermore National Laboratory.',
  },
  {
    z: 117,
    symbol: 'Ts',
    name: 'Tennessine',
    ep: 8000,
    description: 'Named for Tennessee.',
  },
  {
    z: 118,
    symbol: 'Og',
    name: 'Oganesson',
    ep: 25000,
    description: 'Named for Yuri Oganessian; heaviest confirmed element.',
  },
];

function highlightAtomicSlice(n: number): boolean[] {
  const z = atomicNumberFromRoll(n);
  if (z === null) return maskWhere(n, () => false);
  const width = String(z).length;
  return maskWhere(n, (_d, i, s) => i >= s.length - width);
}

export const ATOMIC_REGISTRY_BADGES: BadgeDef[] = ATOMIC_REGISTRY_META.map(
  ({ z, symbol, name, ep, description }) => ({
    id: `atomic-z-${z}`,
    name,
    description,
    ep,
    family: 'atomic-registry' as const,
    emoji: symbol,
    matches: (n: number) => atomicNumberFromRoll(n) === z,
    highlight: highlightAtomicSlice,
  }),
);
