import type { BadgeDef } from '../types';
import {
  digitLength,
  hasBookends,
  isAllSameDigits,
  isAlternating,
  isEven,
  isFibonacci,
  isHarshad,
  isPalindrome,
  isPerfectPower,
  isPowerOfTwo,
  isPrime,
  isStrictlyAscending,
  isStrictlyDescending,
  longestRun,
  pokerHand,
  zeroCount,
} from './matchers';

/** Inspired original number badges — not a copy of RNGdle IP. */
export const NUMBER_BADGES: BadgeDef[] = [
  // --- edges / magnitude ---
  {
    id: 'zero',
    name: 'Absolute Zero',
    description: 'Rolled exactly 0',
    ep: 8_000,
    family: 'magnitude',
    matches: (n) => n === 0,
  },
  {
    id: 'million',
    name: 'Ceiling',
    description: 'Rolled exactly 1,000,000',
    ep: 50_000,
    family: 'magnitude',
    matches: (n) => n === 1_000_000,
  },
  {
    id: 'low-ball',
    name: 'Low Ball',
    description: 'Number is 1–99',
    ep: 400,
    family: 'magnitude',
    matches: (n) => n >= 1 && n <= 99,
  },
  {
    id: 'high-roller',
    name: 'High Roller',
    description: 'Number is 900,000–999,999',
    ep: 350,
    family: 'magnitude',
    matches: (n) => n >= 900_000 && n <= 999_999,
  },
  {
    id: 'one-digit',
    name: 'Single Digit',
    description: '1–9 only',
    ep: 1_200,
    family: 'magnitude',
    matches: (n) => n >= 1 && n <= 9,
  },
  {
    id: 'six-digits',
    name: 'Six Figures',
    description: 'Exactly 6 digits',
    ep: 40,
    family: 'magnitude',
    matches: (n) => digitLength(n) === 6,
  },

  // --- math ---
  {
    id: 'prime',
    name: 'Prime',
    description: 'A prime number',
    ep: 1_200,
    family: 'math',
    matches: isPrime,
  },
  {
    id: 'palindrome',
    name: 'Mirror',
    description: 'Reads the same forwards and backwards',
    ep: 2_500,
    family: 'math',
    matches: isPalindrome,
  },
  {
    id: 'power-of-two',
    name: 'Binary Soul',
    description: 'A power of two',
    ep: 3_000,
    family: 'math',
    matches: isPowerOfTwo,
  },
  {
    id: 'square',
    name: 'Perfect Square',
    description: 'An integer square',
    ep: 900,
    family: 'math',
    matches: (n) => n > 1 && isPerfectPower(n, 2),
  },
  {
    id: 'cube',
    name: 'Perfect Cube',
    description: 'An integer cube',
    ep: 2_000,
    family: 'math',
    matches: (n) => n > 1 && isPerfectPower(n, 3),
  },
  {
    id: 'fibonacci',
    name: 'Fibonacci',
    description: 'A Fibonacci number',
    ep: 2_800,
    family: 'math',
    matches: isFibonacci,
  },
  {
    id: 'harshad',
    name: 'Harshad',
    description: 'Divisible by the sum of its digits',
    ep: 180,
    family: 'math',
    matches: isHarshad,
  },
  {
    id: 'even',
    name: 'Even Keel',
    description: 'Even number',
    ep: 10,
    family: 'math',
    matches: isEven,
  },
  {
    id: 'odd',
    name: 'Odd One',
    description: 'Odd number',
    ep: 10,
    family: 'math',
    matches: (n) => n % 2 === 1,
  },
  {
    id: 'div3',
    name: 'Triad',
    description: 'Divisible by 3',
    ep: 30,
    family: 'math',
    matches: (n) => n > 0 && n % 3 === 0,
  },
  {
    id: 'div7',
    name: 'Lucky Seven',
    description: 'Divisible by 7',
    ep: 80,
    family: 'math',
    matches: (n) => n > 0 && n % 7 === 0,
  },

  // --- cultural ---
  {
    id: 'nice-42',
    name: 'Meaning of Life',
    description: 'Exactly 42',
    ep: 4_000,
    family: 'cultural',
    matches: (n) => n === 42,
  },
  {
    id: 'error-404',
    name: 'Not Found',
    description: 'Exactly 404',
    ep: 3_500,
    family: 'cultural',
    matches: (n) => n === 404,
  },
  {
    id: 'leet-1337',
    name: 'Elite',
    description: 'Exactly 1337',
    ep: 4_500,
    family: 'cultural',
    matches: (n) => n === 1337,
  },
  {
    id: 'beast-666',
    name: 'Beast',
    description: 'Contains 666 as a digit run',
    ep: 1_800,
    family: 'cultural',
    matches: (n) => String(n).includes('666'),
  },
  {
    id: 'nice-69',
    name: 'Nice',
    description: 'Exactly 69',
    ep: 2_000,
    family: 'cultural',
    matches: (n) => n === 69,
  },
  {
    id: 'boom-8008',
    name: 'Vintage Display',
    description: 'Exactly 8008',
    ep: 5_000,
    family: 'cultural',
    matches: (n) => n === 8008,
  },
  {
    id: 'boom-80085',
    name: 'Calculator Classic',
    description: 'Exactly 80085',
    ep: 8_000,
    family: 'cultural',
    matches: (n) => n === 80085,
  },
  {
    id: 'year-2026',
    name: 'This Year',
    description: 'Exactly 2026',
    ep: 3_000,
    family: 'cultural',
    matches: (n) => n === 2026,
  },
  {
    id: 'dozen',
    name: 'Dozen',
    description: 'Exactly 12',
    ep: 1_500,
    family: 'cultural',
    matches: (n) => n === 12,
  },

  // --- patterns / sequences ---
  {
    id: 'all-same-digits',
    name: 'Homogeneous',
    description: 'All digits identical (at least 2)',
    ep: 6_000,
    family: 'pattern',
    matches: isAllSameDigits,
  },
  {
    id: 'ascending',
    name: 'Ascension',
    description: 'Digits strictly increasing',
    ep: 4_500,
    family: 'sequence',
    matches: isStrictlyAscending,
  },
  {
    id: 'descending',
    name: 'Cascade',
    description: 'Digits strictly decreasing',
    ep: 4_500,
    family: 'sequence',
    matches: isStrictlyDescending,
  },
  {
    id: 'alternating',
    name: 'Alternator',
    description: 'Digits alternate between two values',
    ep: 2_200,
    family: 'pattern',
    matches: isAlternating,
  },
  {
    id: 'bookends',
    name: 'Bookends',
    description: 'First and last digit match',
    ep: 200,
    family: 'pattern',
    matches: hasBookends,
  },
  {
    id: 'round-thousand',
    name: 'Round Thousand',
    description: 'Ends with 000 (and not zero)',
    ep: 1_100,
    family: 'void',
    matches: (n) => n >= 1000 && n % 1000 === 0,
  },
  {
    id: 'round-hundred',
    name: 'Century Mark',
    description: 'Ends with 00 (not 000)',
    ep: 250,
    family: 'void',
    matches: (n) => n >= 100 && n % 100 === 0 && n % 1000 !== 0,
  },
  {
    id: 'deep-void',
    name: 'Deep Void',
    description: 'Contains 3 or more zeros',
    ep: 1_400,
    family: 'void',
    matches: (n) => zeroCount(n) >= 3,
  },
  {
    id: 'void',
    name: 'Void',
    description: 'Contains at least one zero',
    ep: 40,
    family: 'void',
    matches: (n) => zeroCount(n) >= 1,
  },
  {
    id: 'run-3',
    name: 'Triple Run',
    description: 'Three identical digits in a row',
    ep: 900,
    family: 'pattern',
    matches: (n) => longestRun(n) >= 3,
  },
  {
    id: 'run-4',
    name: 'Quad Run',
    description: 'Four identical digits in a row',
    ep: 3_500,
    family: 'pattern',
    matches: (n) => longestRun(n) >= 4,
  },
  {
    id: 'run-5',
    name: 'Quint Run',
    description: 'Five identical digits in a row',
    ep: 12_000,
    family: 'pattern',
    matches: (n) => longestRun(n) >= 5,
  },

  // --- poker digit hands ---
  {
    id: 'pair',
    name: 'Pair',
    description: 'Exactly one pair of matching digits',
    ep: 80,
    family: 'poker',
    matches: (n) => pokerHand(n) === 'pair',
  },
  {
    id: 'two-pair',
    name: 'Two Pair',
    description: 'Two different digit pairs',
    ep: 320,
    family: 'poker',
    matches: (n) => pokerHand(n) === 'two-pair',
  },
  {
    id: 'trips',
    name: 'Three of a Kind',
    description: 'Three matching digits',
    ep: 600,
    family: 'poker',
    matches: (n) => pokerHand(n) === 'trips',
  },
  {
    id: 'full-house',
    name: 'Full House',
    description: 'Three of one digit and a pair of another',
    ep: 2_000,
    family: 'poker',
    matches: (n) => pokerHand(n) === 'full-house',
  },
  {
    id: 'quads',
    name: 'Four of a Kind',
    description: 'Four matching digits',
    ep: 4_000,
    family: 'poker',
    matches: (n) => pokerHand(n) === 'quads',
  },
  {
    id: 'five-kind',
    name: 'Five of a Kind',
    description: 'Five matching digits',
    ep: 15_000,
    family: 'poker',
    matches: (n) => pokerHand(n) === 'five',
  },

  // --- more fun ---
  {
    id: 'binary-digits',
    name: 'Bitstream',
    description: 'Only digits 0 and 1',
    ep: 2_500,
    family: 'pattern',
    matches: (n) => /^[01]+$/.test(String(n)) && String(n).length >= 3,
  },
  {
    id: 'lucky-7-digit',
    name: 'Sevens',
    description: 'Contains the digit 7',
    ep: 25,
    family: 'cultural',
    matches: (n) => String(n).includes('7'),
  },
  {
    id: 'mirror-bookends-2',
    name: 'Twin Gates',
    description: 'First two digits equal last two (4+ digits)',
    ep: 1_600,
    family: 'pattern',
    matches: (n) => {
      const s = String(n);
      return s.length >= 4 && s.slice(0, 2) === s.slice(-2);
    },
  },
  {
    id: 'sandwich',
    name: 'Sandwich',
    description: 'Middle digit(s) differ; ends match; length ≥ 3',
    ep: 350,
    family: 'pattern',
    matches: (n) => {
      const s = String(n);
      if (s.length < 3) return false;
      if (s[0] !== s[s.length - 1]) return false;
      const mid = s.slice(1, -1);
      return mid.split('').some((c) => c !== s[0]);
    },
  },
];

export function badgeById(id: string): BadgeDef | undefined {
  return NUMBER_BADGES.find((b) => b.id === id);
}
