import type { BadgeDef } from '../types';
import {
  hasConsecutiveSequence,
  maskAll,
  maskBookends,
  maskConsecutiveSequence,
  maskDigit,
  maskLongestRun,
  maskPairedDigits,
  maskSubstring,
  maskWhere,
  uniqueDigitCount,
} from '../highlights';
import {
  digitLength,
  hasBookends,
  isAllSameDigits,
  isAlternating,
  isEven,
  isFibonacci,
  isHarshad,
  isPalindrome,
  isPerfectPower,
  isPowerOfTwo,
  isPrime,
  isStrictlyAscending,
  isStrictlyDescending,
  longestRun,
  pokerHand,
  zeroCount,
} from './matchers';

/** Inspired original number badges — not a copy of RNGdle IP. */
export const NUMBER_BADGES: BadgeDef[] = [
  // --- edges / magnitude ---
  {
    id: 'zero',
    name: 'Absolute Zero',
    description: 'Rolled exactly 0 — the void itself.',
    ep: 8_000,
    family: 'magnitude',
    emoji: '🧊',
    matches: (n) => n === 0,
  },
  {
    id: 'million',
    name: 'Ceiling',
    description: 'Rolled exactly 1,000,000 — the top of the range.',
    ep: 50_000,
    family: 'magnitude',
    emoji: '👑',
    matches: (n) => n === 1_000_000,
  },
  {
    id: 'low-ball',
    name: 'Low Ball',
    description: 'A tiny number (1–99).',
    ep: 400,
    family: 'magnitude',
    emoji: '🎱',
    matches: (n) => n >= 1 && n <= 99,
  },
  {
    id: 'high-roller',
    name: 'High Roller',
    description: 'A huge number (900,000–999,999).',
    ep: 350,
    family: 'magnitude',
    emoji: '🎲',
    matches: (n) => n >= 900_000 && n <= 999_999,
  },
  {
    id: 'one-digit',
    name: 'Single Digit',
    description: 'Only one digit (1–9).',
    ep: 1_200,
    family: 'magnitude',
    emoji: '1️⃣',
    matches: (n) => n >= 1 && n <= 9,
  },
  {
    id: 'six-digits',
    name: 'Six Figures',
    description: 'Exactly six digits long.',
    ep: 40,
    family: 'magnitude',
    emoji: '📏',
    matches: (n) => digitLength(n) === 6,
  },

  // --- math ---
  {
    id: 'prime',
    name: 'Prime',
    description: 'A prime number — only divisible by 1 and itself.',
    ep: 1_200,
    family: 'math',
    emoji: '🔷',
    matches: isPrime,
  },
  {
    id: 'palindrome',
    name: 'Mirror',
    description: 'Reads the same forwards and backwards.',
    ep: 2_500,
    family: 'math',
    emoji: '🪞',
    matches: isPalindrome,
  },
  {
    id: 'power-of-two',
    name: 'Binary Soul',
    description: 'A pure power of two.',
    ep: 3_000,
    family: 'math',
    emoji: '💻',
    matches: isPowerOfTwo,
  },
  {
    id: 'square',
    name: 'Perfect Square',
    description: 'An integer square (n²).',
    ep: 900,
    family: 'math',
    emoji: '⬜',
    matches: (n) => n > 1 && isPerfectPower(n, 2),
  },
  {
    id: 'cube',
    name: 'Perfect Cube',
    description: 'An integer cube (n³).',
    ep: 2_000,
    family: 'math',
    emoji: '🧊',
    matches: (n) => n > 1 && isPerfectPower(n, 3),
  },
  {
    id: 'fibonacci',
    name: 'Fibonacci',
    description: 'Appears in the Fibonacci sequence.',
    ep: 2_800,
    family: 'math',
    emoji: '🐚',
    matches: isFibonacci,
  },
  {
    id: 'harshad',
    name: 'Harshad',
    description: 'Divisible by the sum of its digits.',
    ep: 180,
    family: 'math',
    emoji: '➕',
    matches: isHarshad,
  },
  {
    id: 'even',
    name: 'Even Keel',
    description: 'An even number.',
    ep: 10,
    family: 'math',
    emoji: '⚖️',
    matches: isEven,
    highlight: (n) => maskWhere(n, (_, i, s) => i === s.length - 1),
  },
  {
    id: 'odd',
    name: 'Odd One',
    description: 'An odd number.',
    ep: 10,
    family: 'math',
    emoji: '🎲',
    matches: (n) => n % 2 === 1,
    highlight: (n) => maskWhere(n, (_, i, s) => i === s.length - 1),
  },
  {
    id: 'div3',
    name: 'Triad',
    description: 'Divisible by 3.',
    ep: 30,
    family: 'math',
    emoji: '🔺',
    matches: (n) => n > 0 && n % 3 === 0,
  },
  {
    id: 'div7',
    name: 'Lucky Seven',
    description: 'Divisible by 7.',
    ep: 80,
    family: 'math',
    emoji: '🍀',
    matches: (n) => n > 0 && n % 7 === 0,
  },

  // --- cultural ---
  {
    id: 'nice-42',
    name: 'Meaning of Life',
    description: 'Exactly 42 — the answer to everything.',
    ep: 4_000,
    family: 'cultural',
    emoji: '🌌',
    matches: (n) => n === 42,
  },
  {
    id: 'error-404',
    name: 'Not Found',
    description: 'Exactly 404 — page missing.',
    ep: 3_500,
    family: 'cultural',
    emoji: '🚫',
    matches: (n) => n === 404,
  },
  {
    id: 'leet-1337',
    name: 'Elite',
    description: 'Exactly 1337 — leet status.',
    ep: 4_500,
    family: 'cultural',
    emoji: '😎',
    matches: (n) => n === 1337,
  },
  {
    id: 'beast-666',
    name: 'Beast',
    description: 'Contains the run "666".',
    ep: 1_800,
    family: 'cultural',
    emoji: '😈',
    matches: (n) => String(n).includes('666'),
    highlight: (n) => maskSubstring(n, '666'),
  },
  {
    id: 'nice-69',
    name: 'Nice',
    description: 'Exactly 69. Nice.',
    ep: 2_000,
    family: 'cultural',
    emoji: '😏',
    matches: (n) => n === 69,
  },
  {
    id: 'six-seven',
    name: 'Six-Seven',
    description: 'Contains the digits "67" in order.',
    ep: 2_024,
    family: 'cultural',
    emoji: '🤙',
    matches: (n) => String(n).includes('67'),
    highlight: (n) => maskSubstring(n, '67'),
  },
  {
    id: 'boom-8008',
    name: 'Vintage Display',
    description: 'Exactly 8008 — calculator classic.',
    ep: 5_000,
    family: 'cultural',
    emoji: '📟',
    matches: (n) => n === 8008,
  },
  {
    id: 'boom-80085',
    name: 'Calculator Classic',
    description: 'Exactly 80085 — peak calculator humor.',
    ep: 8_000,
    family: 'cultural',
    emoji: '😂',
    matches: (n) => n === 80085,
  },
  {
    id: 'year-2026',
    name: 'This Year',
    description: 'Exactly 2026.',
    ep: 3_000,
    family: 'cultural',
    emoji: '📅',
    matches: (n) => n === 2026,
  },
  {
    id: 'dozen',
    name: 'Dozen',
    description: 'Exactly 12.',
    ep: 1_500,
    family: 'cultural',
    emoji: '🥚',
    matches: (n) => n === 12,
  },

  // --- patterns / sequences ---
  {
    id: 'all-same-digits',
    name: 'Homogeneous',
    description: 'All digits are identical (at least 2).',
    ep: 6_000,
    family: 'pattern',
    emoji: '🎯',
    matches: isAllSameDigits,
  },
  {
    id: 'ascending',
    name: 'Ascension',
    description: 'Digits strictly increase left to right.',
    ep: 4_500,
    family: 'sequence',
    emoji: '📈',
    matches: isStrictlyAscending,
  },
  {
    id: 'descending',
    name: 'Cascade',
    description: 'Digits strictly decrease left to right.',
    ep: 4_500,
    family: 'sequence',
    emoji: '📉',
    matches: isStrictlyDescending,
  },
  {
    id: 'sequence-3',
    name: 'Sequence (3)',
    description: 'Contains a run of 3 consecutive digits (up or down).',
    ep: 1_716,
    family: 'sequence',
    emoji: '🔢',
    matches: (n) => hasConsecutiveSequence(n, 3),
    highlight: (n) => maskConsecutiveSequence(n, 3),
  },
  {
    id: 'alternating',
    name: 'Alternator',
    description: 'Digits alternate between two values.',
    ep: 2_200,
    family: 'pattern',
    emoji: '⚡',
    matches: isAlternating,
  },
  {
    id: 'bookends',
    name: 'Bookends',
    description: 'The first and last digits are identical.',
    ep: 200,
    family: 'pattern',
    emoji: '📚',
    matches: hasBookends,
    highlight: maskBookends,
  },
  {
    id: 'sandwich',
    name: 'Sandwich',
    description: 'Ends match and the middle differs — a digit sandwich.',
    ep: 350,
    family: 'pattern',
    emoji: '🥪',
    matches: (n) => {
      const s = String(n);
      if (s.length < 3) return false;
      if (s[0] !== s[s.length - 1]) return false;
      return s.slice(1, -1).split('').some((c) => c !== s[0]);
    },
    highlight: maskBookends,
  },
  {
    id: 'round-thousand',
    name: 'Round Thousand',
    description: 'Ends with 000 (and is not zero).',
    ep: 1_100,
    family: 'void',
    emoji: '🌑',
    matches: (n) => n >= 1000 && n % 1000 === 0,
    highlight: (n) => maskWhere(n, (d, i, s) => i >= s.length - 3),
  },
  {
    id: 'round-hundred',
    name: 'Century Mark',
    description: 'Ends with 00 but not 000.',
    ep: 250,
    family: 'void',
    emoji: '💯',
    matches: (n) => n >= 100 && n % 100 === 0 && n % 1000 !== 0,
    highlight: (n) => maskWhere(n, (d, i, s) => i >= s.length - 2),
  },
  {
    id: 'deep-void',
    name: 'Deep Void',
    description: 'Contains three or more zeros.',
    ep: 1_400,
    family: 'void',
    emoji: '🕳️',
    matches: (n) => zeroCount(n) >= 3,
    highlight: (n) => maskDigit(n, 0),
  },
  {
    id: 'void',
    name: 'Void',
    description: 'Contains at least one zero.',
    ep: 40,
    family: 'void',
    emoji: '⚫',
    matches: (n) => zeroCount(n) >= 1,
    highlight: (n) => maskDigit(n, 0),
  },
  {
    id: 'run-3',
    name: 'Triple Run',
    description: 'Three identical digits in a row.',
    ep: 900,
    family: 'pattern',
    emoji: '3️⃣',
    matches: (n) => longestRun(n) >= 3,
    highlight: maskLongestRun,
  },
  {
    id: 'run-4',
    name: 'Quad Run',
    description: 'Four identical digits in a row.',
    ep: 3_500,
    family: 'pattern',
    emoji: '4️⃣',
    matches: (n) => longestRun(n) >= 4,
    highlight: maskLongestRun,
  },
  {
    id: 'run-5',
    name: 'Quint Run',
    description: 'Five identical digits in a row.',
    ep: 12_000,
    family: 'pattern',
    emoji: '5️⃣',
    matches: (n) => longestRun(n) >= 5,
    highlight: maskLongestRun,
  },

  // --- poker ---
  {
    id: 'pair',
    name: 'Pair',
    description: 'Exactly one pair of matching digits.',
    ep: 80,
    family: 'poker',
    emoji: '🃏',
    matches: (n) => pokerHand(n) === 'pair',
    highlight: maskPairedDigits,
  },
  {
    id: 'two-pair',
    name: 'Two Pair',
    description: 'Two distinct pairs of matching digits.',
    ep: 447,
    family: 'poker',
    emoji: '👥',
    matches: (n) => pokerHand(n) === 'two-pair',
    highlight: maskPairedDigits,
  },
  {
    id: 'trips',
    name: 'Three of a Kind',
    description: 'Three matching digits (not necessarily adjacent).',
    ep: 600,
    family: 'poker',
    emoji: '🎲',
    matches: (n) => pokerHand(n) === 'trips',
    highlight: maskPairedDigits,
  },
  {
    id: 'full-house',
    name: 'Full House',
    description: 'Three of one digit and a pair of another.',
    ep: 2_000,
    family: 'poker',
    emoji: '🏠',
    matches: (n) => pokerHand(n) === 'full-house',
    highlight: maskAll,
  },
  {
    id: 'quads',
    name: 'Four of a Kind',
    description: 'Four matching digits.',
    ep: 4_000,
    family: 'poker',
    emoji: '💎',
    matches: (n) => pokerHand(n) === 'quads',
    highlight: maskPairedDigits,
  },
  {
    id: 'five-kind',
    name: 'Five of a Kind',
    description: 'Five matching digits.',
    ep: 15_000,
    family: 'poker',
    emoji: '🌟',
    matches: (n) => pokerHand(n) === 'five',
    highlight: maskAll,
  },
  {
    id: 'quartet',
    name: 'Quartet',
    description: 'Uses exactly four different digits.',
    ep: 290,
    family: 'poker',
    emoji: '🎻',
    matches: (n) => uniqueDigitCount(n) === 4 && digitLength(n) >= 4,
  },

  // --- more fun ---
  {
    id: 'binary-digits',
    name: 'Bitstream',
    description: 'Only digits 0 and 1 (length ≥ 3).',
    ep: 2_500,
    family: 'pattern',
    emoji: '💾',
    matches: (n) => /^[01]+$/.test(String(n)) && String(n).length >= 3,
  },
  {
    id: 'lucky-7-digit',
    name: 'Sevens',
    description: 'Contains the digit 7.',
    ep: 25,
    family: 'cultural',
    emoji: '7️⃣',
    matches: (n) => String(n).includes('7'),
    highlight: (n) => maskDigit(n, 7),
  },
  {
    id: 'mirror-bookends-2',
    name: 'Twin Gates',
    description: 'First two digits equal the last two (4+ digits).',
    ep: 1_600,
    family: 'pattern',
    emoji: '🚪',
    matches: (n) => {
      const s = String(n);
      return s.length >= 4 && s.slice(0, 2) === s.slice(-2);
    },
    highlight: (n) => {
      const s = String(n);
      const m = Array.from(s, () => false);
      m[0] = m[1] = m[s.length - 2] = m[s.length - 1] = true;
      return m;
    },
  },

  // --- element-ish single-digit counts (fun flavor) ---
  {
    id: 'boron-5',
    name: 'Boron (5)',
    description: 'Contains exactly one digit 5.',
    ep: 282,
    family: 'element',
    emoji: '🩷',
    matches: (n) => (String(n).match(/5/g) ?? []).length === 1,
    highlight: (n) => maskDigit(n, 5),
  },
  {
    id: 'carbon-6',
    name: 'Carbon (6)',
    description: 'Contains exactly one digit 6.',
    ep: 282,
    family: 'element',
    emoji: '✏️',
    matches: (n) => (String(n).match(/6/g) ?? []).length === 1,
    highlight: (n) => maskDigit(n, 6),
  },
  {
    id: 'nitrogen-7',
    name: 'Nitrogen (7)',
    description: 'Contains exactly one digit 7.',
    ep: 282,
    family: 'element',
    emoji: '💨',
    matches: (n) => (String(n).match(/7/g) ?? []).length === 1,
    highlight: (n) => maskDigit(n, 7),
  },
  {
    id: 'oxygen-8',
    name: 'Oxygen (8)',
    description: 'Contains exactly one digit 8.',
    ep: 282,
    family: 'element',
    emoji: '🫧',
    matches: (n) => (String(n).match(/8/g) ?? []).length === 1,
    highlight: (n) => maskDigit(n, 8),
  },
];

export function badgeById(id: string): BadgeDef | undefined {
  return NUMBER_BADGES.find((b) => b.id === id);
}
