import type { BadgeDef } from '../types.js';
import {
  hasConsecutiveSequence,
  maskAll,
  maskBookends,
  maskConsecutiveSequence,
  maskDigit,
  maskLongestRun,
  maskPairedDigits,
  maskSubstring,
  maskWhere,
  uniqueDigitCount,
} from '../highlights.js';
import {
  allEvenDigits,
  allOddDigits,
  allUniqueDigits,
  contains,
  countDigit,
  digitLength,
  digitProduct,
  digitSum,
  digitsOf,
  endsWith,
  hasBookends,
  isAlternating,
  isAllSameDigits,
  isBalanced,
  isCube,
  isDivisibleBy,
  isEven,
  isFactorialDigitSum,
  isFibonacci,
  isHarshad,
  isMirroredHalves,
  isMountain,
  isNonDecreasing,
  isNonIncreasing,
  isOdd,
  isPalindrome,
  isPowerOfTwo,
  isPerfectPower,
  isPrime,
  isPronic,
  isRepeatingBlock,
  isSmoothStep,
  isSquare,
  isStrictlyAscending,
  isStrictlyDescending,
  isTriangular,
  isValley,
  looksLikeTime,
  looksLikeYear,
  longestRun,
  maxDigit,
  minDigit,
  pokerHand,
  startsWith,
  zeroCount,
} from './matchers.js';

function exact(
  id: string,
  name: string,
  value: number,
  ep: number,
  emoji: string,
  description?: string,
): BadgeDef {
  return {
    id,
    name,
    description: description ?? `Exactly ${value.toLocaleString()}.`,
    ep,
    family: 'cultural',
    emoji,
    matches: (n) => n === value,
  };
}

function containsSub(
  id: string,
  name: string,
  sub: string,
  ep: number,
  emoji: string,
  description?: string,
): BadgeDef {
  return {
    id,
    name,
    description: description ?? `Contains "${sub}".`,
    ep,
    family: 'cultural',
    emoji,
    matches: (n) => contains(n, sub),
    highlight: (n) => maskSubstring(n, sub),
  };
}

const ELEMENT_META: { digit: number; name: string; emoji: string }[] = [
  { digit: 0, name: 'Neon (0)', emoji: '💠' },
  { digit: 1, name: 'Hydrogen (1)', emoji: '⚛️' },
  { digit: 2, name: 'Helium (2)', emoji: '🎈' },
  { digit: 3, name: 'Lithium (3)', emoji: '🔋' },
  { digit: 4, name: 'Beryllium (4)', emoji: '💚' },
  { digit: 5, name: 'Boron (5)', emoji: '🩷' },
  { digit: 6, name: 'Carbon (6)', emoji: '✏️' },
  { digit: 7, name: 'Nitrogen (7)', emoji: '💨' },
  { digit: 8, name: 'Oxygen (8)', emoji: '🫧' },
  { digit: 9, name: 'Fluorine (9)', emoji: '🦷' },
];

const elementBadges: BadgeDef[] = ELEMENT_META.flatMap(
  ({ digit, name, emoji }) => [
    {
      id: `element-one-${digit}`,
      name,
      description: `Contains exactly one digit ${digit}.`,
      ep: 280,
      family: 'element' as const,
      emoji,
      matches: (n) => countDigit(n, digit) === 1,
      highlight: (n) => maskDigit(n, digit),
    },
    {
      id: `element-many-${digit}`,
      name: `${name.split(' ')[0]} Swarm`,
      description: `Contains three or more digit ${digit}s.`,
      ep: 900,
      family: 'element' as const,
      emoji,
      matches: (n) => countDigit(n, digit) >= 3,
      highlight: (n) => maskDigit(n, digit),
    },
  ],
);

/** Inspired original number badges — not a copy of RNGdle IP. */
export const NUMBER_BADGES: BadgeDef[] = [
  // ========== magnitude / length ==========
  {
    id: 'zero',
    name: 'Absolute Zero',
    description: 'Rolled exactly 0 — the void itself.',
    ep: 8_000,
    family: 'magnitude',
    emoji: '🧊',
    matches: (n) => n === 0,
  },
  {
    id: 'million',
    name: 'Absolute Ceiling',
    description:
      'Rolled exactly 1,000,000 — the top of the range. ~1 in a million from the main draw, plus a separate free-play jackpot lottery at 1 in 100 million. Custom ultra-rare seal.',
    ep: 100_000,
    family: 'magnitude',
    emoji: '👑',
    image: '/badges/ceiling.jpg',
    matches: (n) => n === 1_000_000,
    highlight: maskAll,
  },
  {
    id: 'one',
    name: 'Unity',
    description: 'Exactly 1.',
    ep: 3_500,
    family: 'magnitude',
    emoji: '1️⃣',
    matches: (n) => n === 1,
  },
  {
    id: 'low-ball',
    name: 'Low Ball',
    description: 'A tiny number (1–99).',
    ep: 450,
    family: 'magnitude',
    emoji: '🎱',
    matches: (n) => n >= 1 && n <= 99,
  },
  {
    id: 'mid-ball',
    name: 'Midfield',
    description: 'Three-digit range (100–999).',
    ep: 80,
    family: 'magnitude',
    emoji: '🎯',
    matches: (n) => n >= 100 && n <= 999,
  },
  {
    id: 'high-roller',
    name: 'High Roller',
    description: 'A huge number (900,000–999,999).',
    ep: 400,
    family: 'magnitude',
    emoji: '🎲',
    matches: (n) => n >= 900_000 && n <= 999_999,
  },
  {
    id: 'top-decile',
    name: 'Top Decile',
    description: 'At least 100,000.',
    ep: 60,
    family: 'magnitude',
    emoji: '📈',
    matches: (n) => n >= 100_000,
  },
  {
    id: 'one-digit',
    name: 'Single Digit',
    description: 'Only one digit (1–9).',
    ep: 1_200,
    family: 'magnitude',
    emoji: '🔹',
    matches: (n) => n >= 1 && n <= 9,
  },
  {
    id: 'two-digits',
    name: 'Double Digits',
    description: 'Exactly two digits.',
    ep: 350,
    family: 'magnitude',
    emoji: '✌️',
    matches: (n) => digitLength(n) === 2,
  },
  {
    id: 'three-digits',
    name: 'Triple Digits',
    description: 'Exactly three digits.',
    ep: 90,
    family: 'magnitude',
    emoji: '3️⃣',
    matches: (n) => digitLength(n) === 3,
  },
  {
    id: 'four-digits',
    name: 'Four Figures',
    description: 'Exactly four digits.',
    ep: 70,
    family: 'magnitude',
    emoji: '4️⃣',
    matches: (n) => digitLength(n) === 4,
  },
  {
    id: 'five-digits',
    name: 'Five Figures',
    description: 'Exactly five digits.',
    ep: 55,
    family: 'magnitude',
    emoji: '5️⃣',
    matches: (n) => digitLength(n) === 5,
  },
  {
    id: 'six-digits',
    name: 'Six Figures',
    description: 'Exactly six digits long.',
    ep: 45,
    family: 'magnitude',
    emoji: '📏',
    matches: (n) => digitLength(n) === 6,
  },
  {
    id: 'seven-digits',
    name: 'Seven Heaven',
    description: 'Seven digits — only 1,000,000 qualifies.',
    ep: 50_000,
    family: 'magnitude',
    emoji: '🌈',
    matches: (n) => digitLength(n) === 7,
  },

  // ========== math ==========
  {
    id: 'prime',
    name: 'Prime',
    description: 'A prime number — only divisible by 1 and itself.',
    ep: 1_400,
    family: 'math',
    emoji: '🔷',
    matches: isPrime,
  },
  {
    id: 'palindrome',
    name: 'Mirror',
    description: 'Reads the same forwards and backwards.',
    ep: 2_600,
    family: 'math',
    emoji: '🪞',
    matches: isPalindrome,
  },
  {
    id: 'power-of-two',
    name: 'Binary Soul',
    description: 'A pure power of two.',
    ep: 2_800,
    family: 'math',
    emoji: '💻',
    matches: isPowerOfTwo,
  },
  {
    id: 'square',
    name: 'Perfect Square',
    description: 'An integer square (n²).',
    ep: 850,
    family: 'math',
    emoji: '⬜',
    matches: (n) => n > 1 && isSquare(n),
  },
  {
    id: 'cube',
    name: 'Perfect Cube',
    description: 'An integer cube (n³).',
    ep: 1_800,
    family: 'math',
    emoji: '🧊',
    matches: (n) => n > 1 && isCube(n),
  },
  {
    id: 'fourth-power',
    name: 'Fourth Power',
    description: 'A perfect fourth power (n⁴).',
    ep: 4_000,
    family: 'math',
    emoji: '4️⃣',
    matches: (n) => n > 1 && isPerfectPower(n, 4),
  },
  {
    id: 'fibonacci',
    name: 'Fibonacci',
    description: 'Appears in the Fibonacci sequence.',
    ep: 2_500,
    family: 'math',
    emoji: '🐚',
    matches: isFibonacci,
  },
  {
    id: 'triangular',
    name: 'Triangular',
    description: 'A triangular number (1, 3, 6, 10, …).',
    ep: 700,
    family: 'math',
    emoji: '📐',
    matches: (n) => n > 0 && isTriangular(n),
  },
  {
    id: 'pronic',
    name: 'Pronic',
    description: 'A pronic number n = k(k+1).',
    ep: 900,
    family: 'math',
    emoji: '🔗',
    matches: (n) => n > 0 && isPronic(n),
  },
  {
    id: 'harshad',
    name: 'Harshad',
    description: 'Divisible by the sum of its digits.',
    ep: 160,
    family: 'math',
    emoji: '➕',
    matches: isHarshad,
  },
  {
    id: 'even',
    name: 'Even Keel',
    description: 'An even number.',
    ep: 8,
    family: 'math',
    emoji: '⚖️',
    matches: isEven,
    highlight: (n) => maskWhere(n, (_d, i, s) => i === s.length - 1),
  },
  {
    id: 'odd',
    name: 'Odd One',
    description: 'An odd number.',
    ep: 8,
    family: 'math',
    emoji: '🎲',
    matches: isOdd,
    highlight: (n) => maskWhere(n, (_d, i, s) => i === s.length - 1),
  },
  {
    id: 'div3',
    name: 'Triad',
    description: 'Divisible by 3.',
    ep: 35,
    family: 'math',
    emoji: '🔺',
    matches: (n) => isDivisibleBy(n, 3),
  },
  {
    id: 'div4',
    name: 'Quad Div',
    description: 'Divisible by 4.',
    ep: 50,
    family: 'math',
    emoji: '▦',
    matches: (n) => isDivisibleBy(n, 4),
  },
  {
    id: 'div5',
    name: 'High Five',
    description: 'Divisible by 5.',
    ep: 55,
    family: 'math',
    emoji: '🖐️',
    matches: (n) => isDivisibleBy(n, 5),
  },
  {
    id: 'div7',
    name: 'Lucky Seven',
    description: 'Divisible by 7.',
    ep: 90,
    family: 'math',
    emoji: '🍀',
    matches: (n) => isDivisibleBy(n, 7),
  },
  {
    id: 'div8',
    name: 'Octave',
    description: 'Divisible by 8.',
    ep: 95,
    family: 'math',
    emoji: '🎵',
    matches: (n) => isDivisibleBy(n, 8),
  },
  {
    id: 'div9',
    name: 'Cloud Nine',
    description: 'Divisible by 9.',
    ep: 100,
    family: 'math',
    emoji: '☁️',
    matches: (n) => isDivisibleBy(n, 9),
  },
  {
    id: 'div11',
    name: 'Elevensies',
    description: 'Divisible by 11.',
    ep: 140,
    family: 'math',
    emoji: '1️⃣1️⃣',
    matches: (n) => isDivisibleBy(n, 11),
  },
  {
    id: 'div12',
    name: 'Dozenal',
    description: 'Divisible by 12.',
    ep: 120,
    family: 'math',
    emoji: '🥚',
    matches: (n) => isDivisibleBy(n, 12),
  },
  {
    id: 'div13',
    name: 'Unlucky Math',
    description: 'Divisible by 13.',
    ep: 160,
    family: 'math',
    emoji: '🦇',
    matches: (n) => isDivisibleBy(n, 13),
  },
  {
    id: 'div25',
    name: 'Quarter Century',
    description: 'Divisible by 25.',
    ep: 200,
    family: 'math',
    emoji: '🪙',
    matches: (n) => isDivisibleBy(n, 25),
  },
  {
    id: 'div100',
    name: 'Round Hundred',
    description: 'Divisible by 100.',
    ep: 280,
    family: 'math',
    emoji: '💯',
    matches: (n) => isDivisibleBy(n, 100),
  },
  {
    id: 'div1000',
    name: 'Kiloblock',
    description: 'Divisible by 1,000.',
    ep: 900,
    family: 'math',
    emoji: '📦',
    matches: (n) => isDivisibleBy(n, 1000),
  },
  {
    id: 'digit-sum-10',
    name: 'Perfect Ten',
    description: 'Digits sum to exactly 10.',
    ep: 320,
    family: 'math',
    emoji: '🔟',
    matches: (n) => digitSum(n) === 10,
  },
  {
    id: 'digit-sum-21',
    name: 'Blackjack Sum',
    description: 'Digits sum to 21.',
    ep: 450,
    family: 'math',
    emoji: '🃏',
    matches: (n) => digitSum(n) === 21,
  },
  {
    id: 'digit-sum-high',
    name: 'Heavy',
    description: 'Digit sum is 40 or more.',
    ep: 1_200,
    family: 'math',
    emoji: '🏋️',
    matches: (n) => digitSum(n) >= 40,
  },
  {
    id: 'digit-sum-low',
    name: 'Feather',
    description: 'Digit sum is 5 or less (and n ≥ 10).',
    ep: 1_000,
    family: 'math',
    emoji: '🪶',
    matches: (n) => n >= 10 && digitSum(n) <= 5,
  },
  {
    id: 'digit-product-0',
    name: 'Null Product',
    description: 'Digit product is zero (contains a 0).',
    ep: 35,
    family: 'math',
    emoji: '✖️',
    matches: (n) => digitProduct(n) === 0 && n > 0,
  },
  {
    id: 'factorial-curious',
    name: 'Factorial Curious',
    description: 'A rare factorial-digit sum number (e.g. 145).',
    ep: 6_000,
    family: 'math',
    emoji: '❗',
    matches: isFactorialDigitSum,
  },

  // ========== cultural / meme / constants ==========
  exact('nice-42', 'Meaning of Life', 42, 4_000, '🌌'),
  exact('error-404', 'Not Found', 404, 3_500, '🚫'),
  exact('leet-1337', 'Elite', 1337, 4_500, '😎'),
  exact('nice-69', 'Nice', 69, 2_000, '😏'),
  exact('boom-8008', 'Vintage Display', 8008, 5_000, '📟'),
  exact('boom-80085', 'Calculator Classic', 80085, 8_000, '😂'),
  exact('year-2026', 'This Year', 2026, 3_000, '📅'),
  exact('dozen', 'Dozen', 12, 1_500, '🥚'),
  exact('gross', 'Gross', 144, 1_800, '📦'),
  exact('score', 'Score', 20, 1_200, '🎯'),
  exact('pi-slice', 'Pi Slice', 314, 2_200, '🥧'),
  exact('pi-long', 'Pi Party', 31415, 5_500, '🥧'),
  exact('e-slice', 'Euler Nibble', 271, 2_200, '𝑒'),
  exact('e-long', 'Euler Feast', 27182, 5_500, '𝑒'),
  exact('golden', 'Golden Cut', 1618, 3_000, '✨'),
  exact('binary-max-byte', 'Full Byte', 255, 1_600, '💾'),
  exact('kib', 'Kibibyte', 1024, 2_000, '🖥️'),
  exact('www', 'World Wide', 333, 1_400, '🌐'),
  exact('bbb', 'Triple B', 222, 1_200, '🅱️'),
  exact('aaa', 'Triple A', 111, 1_200, '🅰️'),
  exact('zzz', 'Triple Z', 999, 1_500, '💤'),
  exact('half-life', 'Half-Life', 3, 2_000, '🧪'),
  exact('lucky-7', 'Seven Alone', 7, 2_500, '7️⃣'),
  exact('unlucky-13', 'Thirteen', 13, 2_200, '🦇'),
  exact('sweet-16', 'Sweet Sixteen', 16, 1_800, '🎂'),
  exact('twenty-one', 'Blackjack', 21, 1_600, '🂡'),
  exact('answer-420', 'Blaze', 420, 2_800, '🌿'),
  exact('beast-exact', 'Number of the Beast', 666, 3_500, '😈'),
  exact('angel-777', 'Jackpot Sevens', 777, 3_200, '🎰'),
  exact('lucky-888', 'Triple Fortune', 888, 3_200, '🧧'),
  exact('end-times', 'Almost There', 999999, 6_000, '⏳'),
  exact('power-ball', 'Powerball', 58, 1_400, '🎱'),
  exact('pi-day', 'Pi Day', 314159, 8_000, '🥧'),
  exact('leet-speak', 'Leetspeak Lite', 133, 1_500, '🤓'),
  exact('boobies', 'Calculator Classic II', 58008, 7_000, '📱'),

  containsSub(
    'beast-666',
    'Beast',
    '666',
    1_800,
    '😈',
    'Contains the run "666".',
  ),
  containsSub('six-seven', 'Six-Seven', '67', 2_024, '🤙'),
  containsSub('angel-run', 'Heavenly Run', '777', 2_200, '😇'),
  containsSub('fortune-run', 'Fortune Run', '888', 2_200, '💰'),
  containsSub('leet-run', 'Leet Run', '1337', 3_500, '👾'),
  containsSub('pi-run', 'Pi Run', '314', 900, '🥧'),
  containsSub('e-run', 'E Run', '271', 900, '𝑒'),
  containsSub('year-20', 'Century Mark Y2K', '20', 120, '📅', 'Contains "20".'),
  containsSub('boom-69', 'Nice Hidden', '69', 600, '😏'),
  containsSub('boom-420', 'Herbal Hidden', '420', 900, '🌿'),
  containsSub('binary-10', 'Bit Flip', '10', 80, '🔀', 'Contains "10".'),
  containsSub('binary-01', 'Bit Flip II', '01', 100, '🔀', 'Contains "01".'),
  containsSub('stairs-123', 'Staircase', '123', 700, '📶'),
  containsSub('stairs-321', 'Downstairs', '321', 700, '📶'),
  containsSub('stairs-456', 'Mid Stairs', '456', 700, '📶'),
  containsSub('stairs-789', 'High Stairs', '789', 700, '📶'),
  containsSub('zoom-000', 'Triple Void', '000', 1_500, '🕳️'),
  containsSub('zoom-111', 'Triple Ones', '111', 800, '1️⃣'),
  containsSub('zoom-222', 'Triple Twos', '222', 800, '2️⃣'),
  containsSub('zoom-333', 'Triple Threes', '333', 800, '3️⃣'),
  containsSub('zoom-444', 'Triple Fours', '444', 800, '4️⃣'),
  containsSub('zoom-555', 'Triple Fives', '555', 800, '5️⃣'),
  containsSub('zoom-999', 'Triple Nines', '999', 900, '9️⃣'),

  // fix: remove the bad exact hello badge - I'll not include it
  // ========== patterns / sequences ==========
  {
    id: 'all-same-digits',
    name: 'Homogeneous',
    description: 'All digits are identical (at least 2).',
    ep: 5_500,
    family: 'pattern',
    emoji: '🎯',
    matches: isAllSameDigits,
  },
  {
    id: 'ascending',
    name: 'Ascension',
    description: 'Digits strictly increase left to right.',
    ep: 4_000,
    family: 'sequence',
    emoji: '📈',
    matches: isStrictlyAscending,
  },
  {
    id: 'descending',
    name: 'Cascade',
    description: 'Digits strictly decrease left to right.',
    ep: 4_000,
    family: 'sequence',
    emoji: '📉',
    matches: isStrictlyDescending,
  },
  {
    id: 'sorted-up',
    name: 'Sorted Up',
    description: 'Digits never decrease (weakly ascending).',
    ep: 1_400,
    family: 'sequence',
    emoji: '⬆️',
    matches: isNonDecreasing,
  },
  {
    id: 'sorted-down',
    name: 'Sorted Down',
    description: 'Digits never increase (weakly descending).',
    ep: 1_400,
    family: 'sequence',
    emoji: '⬇️',
    matches: isNonIncreasing,
  },
  {
    id: 'sequence-3',
    name: 'Sequence (3)',
    description: 'Contains a run of 3 consecutive digits (up or down).',
    ep: 1_200,
    family: 'sequence',
    emoji: '🔢',
    matches: (n) => hasConsecutiveSequence(n, 3),
    highlight: (n) => maskConsecutiveSequence(n, 3),
  },
  {
    id: 'sequence-4',
    name: 'Sequence (4)',
    description: 'Contains a run of 4 consecutive digits.',
    ep: 3_500,
    family: 'sequence',
    emoji: '🔢',
    matches: (n) => hasConsecutiveSequence(n, 4),
    highlight: (n) => maskConsecutiveSequence(n, 4),
  },
  {
    id: 'alternating',
    name: 'Alternator',
    description: 'Digits alternate between two values.',
    ep: 2_000,
    family: 'pattern',
    emoji: '⚡',
    matches: isAlternating,
  },
  {
    id: 'bookends',
    name: 'Bookends',
    description: 'The first and last digits are identical.',
    ep: 180,
    family: 'pattern',
    emoji: '📚',
    matches: hasBookends,
    highlight: maskBookends,
  },
  {
    id: 'sandwich',
    name: 'Sandwich',
    description: 'Ends match and the middle differs.',
    ep: 320,
    family: 'pattern',
    emoji: '🥪',
    matches: (n) => {
      const s = digitsOf(n);
      if (s.length < 3) return false;
      if (s[0] !== s[s.length - 1]) return false;
      return s
        .slice(1, -1)
        .split('')
        .some((c) => c !== s[0]);
    },
    highlight: maskBookends,
  },
  {
    id: 'mirror-halves',
    name: 'Twin Halves',
    description: 'First half mirrors the second half.',
    ep: 2_400,
    family: 'pattern',
    emoji: '☯️',
    matches: isMirroredHalves,
  },
  {
    id: 'mountain',
    name: 'Mountain',
    description: 'Digits rise then fall (a peak).',
    ep: 1_600,
    family: 'pattern',
    emoji: '⛰️',
    matches: isMountain,
  },
  {
    id: 'valley',
    name: 'Valley',
    description: 'Digits fall then rise (a trough).',
    ep: 1_600,
    family: 'pattern',
    emoji: '🏞️',
    matches: isValley,
  },
  {
    id: 'smooth-step',
    name: 'Smooth Step',
    description: 'Every adjacent pair differs by exactly 1.',
    ep: 2_800,
    family: 'pattern',
    emoji: '🪜',
    matches: isSmoothStep,
  },
  {
    id: 'all-unique',
    name: 'Heterogeneous',
    description: 'All digits are unique (length ≥ 3).',
    ep: 500,
    family: 'pattern',
    emoji: '🌈',
    matches: allUniqueDigits,
  },
  {
    id: 'balanced',
    name: 'Equilibrium',
    description: 'Left-half digit sum equals right-half digit sum.',
    ep: 1_000,
    family: 'pattern',
    emoji: '⚖️',
    matches: isBalanced,
  },
  {
    id: 'repeating-block',
    name: 'Echo',
    description: 'Made of a repeating digit block (e.g. 121212).',
    ep: 2_600,
    family: 'pattern',
    emoji: '📢',
    matches: isRepeatingBlock,
  },
  {
    id: 'all-even-digits',
    name: 'Even Party',
    description: 'Every digit is even.',
    ep: 700,
    family: 'pattern',
    emoji: '🔵',
    matches: allEvenDigits,
  },
  {
    id: 'all-odd-digits',
    name: 'Odd Party',
    description: 'Every digit is odd.',
    ep: 700,
    family: 'pattern',
    emoji: '🟠',
    matches: allOddDigits,
  },
  {
    id: 'round-thousand',
    name: 'Round Thousand',
    description: 'Ends with 000 (and is not zero).',
    ep: 1_100,
    family: 'void',
    emoji: '🌑',
    matches: (n) => n >= 1000 && n % 1000 === 0,
    highlight: (n) => maskWhere(n, (_d, i, s) => i >= s.length - 3),
  },
  {
    id: 'round-hundred',
    name: 'Century Mark',
    description: 'Ends with 00 but not 000.',
    ep: 250,
    family: 'void',
    emoji: '💯',
    matches: (n) => n >= 100 && n % 100 === 0 && n % 1000 !== 0,
    highlight: (n) => maskWhere(n, (_d, i, s) => i >= s.length - 2),
  },
  {
    id: 'ends-0',
    name: 'Round Off',
    description: 'Ends with a zero.',
    ep: 40,
    family: 'void',
    emoji: '⭕',
    matches: (n) => n > 0 && endsWith(n, '0'),
    highlight: (n) => maskWhere(n, (_d, i, s) => i === s.length - 1),
  },
  {
    id: 'deep-void',
    name: 'Deep Void',
    description: 'Contains three or more zeros.',
    ep: 1_400,
    family: 'void',
    emoji: '🕳️',
    matches: (n) => zeroCount(n) >= 3,
    highlight: (n) => maskDigit(n, 0),
  },
  {
    id: 'void',
    name: 'Void',
    description: 'Contains at least one zero.',
    ep: 28,
    family: 'void',
    emoji: '⚫',
    matches: (n) => zeroCount(n) >= 1,
    highlight: (n) => maskDigit(n, 0),
  },
  {
    id: 'double-void',
    name: 'Double Void',
    description: 'Contains exactly two zeros.',
    ep: 450,
    family: 'void',
    emoji: '🌑',
    matches: (n) => zeroCount(n) === 2,
    highlight: (n) => maskDigit(n, 0),
  },
  {
    id: 'run-2',
    name: 'Double Run',
    description: 'Two identical digits in a row.',
    ep: 90,
    family: 'pattern',
    emoji: '2️⃣',
    matches: (n) => longestRun(n) >= 2,
    highlight: maskLongestRun,
  },
  {
    id: 'run-3',
    name: 'Triple Run',
    description: 'Three identical digits in a row.',
    ep: 850,
    family: 'pattern',
    emoji: '3️⃣',
    matches: (n) => longestRun(n) >= 3,
    highlight: maskLongestRun,
  },
  {
    id: 'run-4',
    name: 'Quad Run',
    description: 'Four identical digits in a row.',
    ep: 3_200,
    family: 'pattern',
    emoji: '4️⃣',
    matches: (n) => longestRun(n) >= 4,
    highlight: maskLongestRun,
  },
  {
    id: 'run-5',
    name: 'Quint Run',
    description: 'Five identical digits in a row.',
    ep: 10_000,
    family: 'pattern',
    emoji: '5️⃣',
    matches: (n) => longestRun(n) >= 5,
    highlight: maskLongestRun,
  },
  {
    id: 'starts-1',
    name: 'Leading One',
    description: 'Starts with 1.',
    ep: 50,
    family: 'pattern',
    emoji: '1️⃣',
    matches: (n) => startsWith(n, '1'),
    highlight: (n) => maskWhere(n, (_d, i) => i === 0),
  },
  {
    id: 'starts-9',
    name: 'Leading Nine',
    description: 'Starts with 9.',
    ep: 90,
    family: 'pattern',
    emoji: '9️⃣',
    matches: (n) => startsWith(n, '9'),
    highlight: (n) => maskWhere(n, (_d, i) => i === 0),
  },
  {
    id: 'ends-7',
    name: 'Lucky Ending',
    description: 'Ends with 7.',
    ep: 80,
    family: 'pattern',
    emoji: '🍀',
    matches: (n) => endsWith(n, '7'),
    highlight: (n) => maskWhere(n, (_d, i, s) => i === s.length - 1),
  },
  {
    id: 'ends-9',
    name: 'Niner',
    description: 'Ends with 9.',
    ep: 70,
    family: 'pattern',
    emoji: '9️⃣',
    matches: (n) => endsWith(n, '9'),
    highlight: (n) => maskWhere(n, (_d, i, s) => i === s.length - 1),
  },
  {
    id: 'max-digit-9',
    name: 'Peak Nine',
    description: 'Highest digit is 9.',
    ep: 40,
    family: 'pattern',
    emoji: '🏔️',
    matches: (n) => maxDigit(n) === 9,
  },
  {
    id: 'min-digit-1',
    name: 'Floor One',
    description: 'Lowest digit is 1 (no zeros).',
    ep: 200,
    family: 'pattern',
    emoji: '⬇️',
    matches: (n) => minDigit(n) === 1,
  },

  // ========== poker ==========
  {
    id: 'pair',
    name: 'Pair',
    description: 'Exactly one pair of matching digits.',
    ep: 55,
    family: 'poker',
    emoji: '🃏',
    matches: (n) => pokerHand(n) === 'pair',
    highlight: maskPairedDigits,
  },
  {
    id: 'two-pair',
    name: 'Two Pair',
    description: 'Two distinct pairs of matching digits.',
    ep: 400,
    family: 'poker',
    emoji: '👥',
    matches: (n) => pokerHand(n) === 'two-pair',
    highlight: maskPairedDigits,
  },
  {
    id: 'trips',
    name: 'Three of a Kind',
    description: 'Three matching digits.',
    ep: 550,
    family: 'poker',
    emoji: '🎲',
    matches: (n) => pokerHand(n) === 'trips',
    highlight: maskPairedDigits,
  },
  {
    id: 'full-house',
    name: 'Full House',
    description: 'Three of one digit and a pair of another.',
    ep: 1_800,
    family: 'poker',
    emoji: '🏠',
    matches: (n) => pokerHand(n) === 'full-house',
    highlight: maskAll,
  },
  {
    id: 'quads',
    name: 'Four of a Kind',
    description: 'Four matching digits.',
    ep: 3_500,
    family: 'poker',
    emoji: '💎',
    matches: (n) => pokerHand(n) === 'quads',
    highlight: maskPairedDigits,
  },
  {
    id: 'five-kind',
    name: 'Five of a Kind',
    description: 'Five matching digits.',
    ep: 12_000,
    family: 'poker',
    emoji: '🌟',
    matches: (n) => pokerHand(n) === 'five',
    highlight: maskAll,
  },
  {
    id: 'six-kind',
    name: 'Six of a Kind',
    description: 'Six matching digits.',
    ep: 25_000,
    family: 'poker',
    emoji: '🌌',
    matches: (n) => pokerHand(n) === 'six',
    highlight: maskAll,
  },
  {
    id: 'quartet',
    name: 'Quartet',
    description: 'Uses exactly four different digits.',
    ep: 260,
    family: 'poker',
    emoji: '🎻',
    matches: (n) => uniqueDigitCount(n) === 4 && digitLength(n) >= 4,
  },
  {
    id: 'trio-unique',
    name: 'Trio Palette',
    description: 'Uses exactly three different digits.',
    ep: 220,
    family: 'poker',
    emoji: '🎨',
    matches: (n) => uniqueDigitCount(n) === 3 && digitLength(n) >= 3,
  },
  {
    id: 'duo-unique',
    name: 'Duo Palette',
    description: 'Uses exactly two different digits.',
    ep: 600,
    family: 'poker',
    emoji: '🎭',
    matches: (n) => uniqueDigitCount(n) === 2 && digitLength(n) >= 2,
  },
  {
    id: 'solo-unique',
    name: 'Mono',
    description: 'Uses exactly one distinct digit (same as homogeneous).',
    ep: 5_000,
    family: 'poker',
    emoji: '⚪',
    matches: (n) => uniqueDigitCount(n) === 1 && digitLength(n) >= 2,
  },
  {
    id: 'full-house-unique',
    name: 'Rainbow Six',
    description: 'Six digits, all unique.',
    ep: 2_000,
    family: 'poker',
    emoji: '🌈',
    matches: (n) => digitLength(n) === 6 && uniqueDigitCount(n) === 6,
  },

  // ========== time / calendar flavor ==========
  {
    id: 'clock',
    name: 'Clockface',
    description: 'Looks like a valid 24h time (HHMM).',
    ep: 900,
    family: 'cultural',
    emoji: '🕐',
    matches: looksLikeTime,
  },
  {
    id: 'modern-year',
    name: 'Modern Year',
    description: 'A year between 1900 and 2099.',
    ep: 1_100,
    family: 'cultural',
    emoji: '📆',
    matches: looksLikeYear,
  },

  // ========== binary-ish ==========
  {
    id: 'binary-digits',
    name: 'Bitstream',
    description: 'Only digits 0 and 1 (length ≥ 3).',
    ep: 2_200,
    family: 'pattern',
    emoji: '💾',
    matches: (n) => /^[01]+$/.test(digitsOf(n)) && digitsOf(n).length >= 3,
  },
  {
    id: 'ternary-digits',
    name: 'Tritstream',
    description: 'Only digits 0, 1, and 2 (length ≥ 4).',
    ep: 1_200,
    family: 'pattern',
    emoji: '📟',
    matches: (n) => /^[012]+$/.test(digitsOf(n)) && digitsOf(n).length >= 4,
  },

  {
    id: 'lucky-7-digit',
    name: 'Sevens',
    description: 'Contains the digit 7.',
    ep: 30,
    family: 'cultural',
    emoji: '7️⃣',
    matches: (n) => digitsOf(n).includes('7'),
    highlight: (n) => maskDigit(n, 7),
  },
  {
    id: 'mirror-bookends-2',
    name: 'Twin Gates',
    description: 'First two digits equal the last two (4+ digits).',
    ep: 1_500,
    family: 'pattern',
    emoji: '🚪',
    matches: (n) => {
      const s = digitsOf(n);
      return s.length >= 4 && s.slice(0, 2) === s.slice(-2);
    },
    highlight: (n) => {
      const s = digitsOf(n);
      const m = Array.from(s, () => false);
      m[0] = m[1] = m[s.length - 2] = m[s.length - 1] = true;
      return m;
    },
  },

  // elements (20 badges: one + swarm × 10)
  ...elementBadges,

  // ========== special / ultra-rare flavor ==========
  {
    id: 'royal-flush-digits',
    name: 'Royal Digits',
    description:
      'Contains 10, J-ish 11 run feel — has both 10 and 11 as substrings.',
    ep: 3_200,
    family: 'cultural',
    emoji: '🃏',
    matches: (n) => contains(n, '10') && contains(n, '11'),
  },
  {
    id: 'chaos-theory',
    name: 'Chaos Theory',
    description: 'Six digits, all unique, neither sorted up nor down.',
    ep: 2_800,
    family: 'pattern',
    emoji: '🌪️',
    matches: (n) =>
      digitLength(n) === 6 &&
      uniqueDigitCount(n) === 6 &&
      !isNonDecreasing(n) &&
      !isNonIncreasing(n),
  },
  {
    id: 'symmetric-sum',
    name: 'Symmetric Sum',
    description: 'Palindrome whose digits also sum to a perfect square.',
    ep: 4_500,
    family: 'math',
    emoji: '🔮',
    matches: (n) => {
      if (!isPalindrome(n)) return false;
      const s = digitSum(n);
      const r = Math.round(Math.sqrt(s));
      return r * r === s;
    },
  },
  {
    id: 'twin-prime-adjacent',
    name: 'Twin Gate Prime',
    description: 'Prime number that also has matching bookend digits.',
    ep: 3_800,
    family: 'math',
    emoji: '🚪',
    matches: (n) => isPrime(n) && hasBookends(n),
  },
  {
    id: 'lucky-streak-num',
    name: 'Lucky Streak Number',
    description: 'Contains three 7s (not necessarily adjacent).',
    ep: 2_400,
    family: 'cultural',
    emoji: '🎰',
    matches: (n) => countDigit(n, 7) >= 3,
    highlight: (n) => maskDigit(n, 7),
  },
  {
    id: 'void-walker',
    name: 'Void Walker',
    description: 'Ends with 0 and contains at least two zeros.',
    ep: 1_100,
    family: 'void',
    emoji: '🌑',
    matches: (n) => n >= 10 && endsWith(n, '0') && zeroCount(n) >= 2,
    highlight: (n) => maskDigit(n, 0),
  },
  {
    id: 'midpoint-king',
    name: 'Midpoint King',
    description: 'Number is within 1% of 500,000 (495000–505000).',
    ep: 2_000,
    family: 'magnitude',
    emoji: '👑',
    matches: (n) => n >= 495_000 && n <= 505_000,
  },
  {
    id: 'almost-ceiling',
    name: 'Almost Ceiling',
    description: 'At least 990,000 but not 1,000,000.',
    ep: 1_800,
    family: 'magnitude',
    emoji: '🪜',
    matches: (n) => n >= 990_000 && n < 1_000_000,
  },
  {
    id: 'binary-palindrome',
    name: 'Bit Mirror',
    description: 'Only 0/1 digits and a palindrome (length ≥ 3).',
    ep: 5_500,
    family: 'pattern',
    emoji: '🪞',
    matches: (n) =>
      /^[01]+$/.test(digitsOf(n)) && digitsOf(n).length >= 3 && isPalindrome(n),
  },
  {
    id: 'year-of-roll',
    name: 'Timestamp Soul',
    description: 'Exactly the current calendar year.',
    ep: 3_500,
    family: 'cultural',
    emoji: '📅',
    matches: (n) => n === new Date().getFullYear(),
  },
];

export function badgeById(id: string): BadgeDef | undefined {
  return NUMBER_BADGES.find((b) => b.id === id);
}
