/// <reference types="node" />
import { writeFileSync } from 'node:fs';
import { NUMBER_BADGES } from '../src/game/badges/catalog.ts';
import { JOURNEY_BADGES } from '../src/game/journey.ts';

const sections = [
  'math',
  'pattern',
  'void',
  'cultural',
  'magnitude',
  'sequence',
  'poker',
  'element',
  'bases',
] as const;

const out: Record<string, string[]> = {};
for (const s of sections) {
  out[s] = NUMBER_BADGES.filter((b) => b.family === s).map((b) => b.id);
}
out.journey = JOURNEY_BADGES.map((b) => b.id);

const ts = `/** Auto-generated by scripts/dump-section-ids.mts — do not edit by hand. */
export const sectionBadgeIds = ${JSON.stringify(out, null, 2)} as const;
export type SectionKey = keyof typeof sectionBadgeIds;
`;
writeFileSync(new URL('../server/sectionBadgeIds.ts', import.meta.url), ts);
writeFileSync(
  new URL('../server/sectionBadgeIds.json', import.meta.url),
  JSON.stringify(out, null, 2),
);
console.log(
  'wrote sectionBadgeIds.ts',
  Object.fromEntries(Object.entries(out).map(([k, v]) => [k, v.length])),
);
